# Generated by Django 3.0.4 on 2020-08-14 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedone',
            field=models.ManyToManyField(related_name='users_post_main', to=settings.AUTH_USER_MODEL, verbose_name='Добавивший пользователь'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnumber',
            field=models.IntegerField(default=0, help_text='Начинается с 1', verbose_name='Количество лайков'),
        ),
    ]
